language: bash

services:
  - docker

env:
  global:
    - SUNSTONE_VERSION: '0.7.2'
    - KUBECTL_VERSION: '1.19.4'
    - secure: GN9WWj4RpfCyU35qLtCGOjBoTxrM7qUvNM5pJne162dW3+hhmy1ZUPxfnkdKGIdzPNd6tXaWOo4P0wffwkXXVXlUrO3HCwD1vYD/eZou/QJ4vM9T96bS/llLoRtRMdAu36wnVvpTyN3FXnMA+4aRE1iGyeYSeZVpGJf8X4cRgpgvJCabEGrtkgk0dDaneETIIGhwiTg3d2TMTNv4bMacGqG04zGNrbEmaEkK9VmmPvSHF7P062LC9IYlWjI05N2/NHvb3SXZEiAvJGvykALc5T427c2UIDXlN6AvTLwITDa9yLtHQLhoFwMIu/7ikj2Ij5LjmyNI0J+FXb6BGx+Rg/oB8hH86VMwdHion3HhA075BfVFWSb8TylFRM+T4QzQOH4C+NRamexcF32NYv2+Yk0DjHpa99ehVky7TPNmJShCmvQCh2RCRAFePjylBvjFiIHpt2KKegU8mqEkSqWyWQ2wAjYGEsj8Q4BMOCFEAbxfJNL5olHJv1i+w2cG49ceT+/F8ehxKkolWAfJFYqnHF7oNpnAz9vKYAo7bUmxVm1gPRlbyGKyinyw0P13qsH9Y+UjwvfllgTwEu2ofegMP4x8nfYG+HsLhNYRM0BaUwFeOWZ3CSDR/Qm4Q19mtzAvQTTx18lWpbO+zJG2V0jltvHnpld/GvdTSfb6dDaeivg=
    - secure: r/IiQWA5it0MhPGeXYeo0sDm7LKI+JcniIccmvQtb2bmL8Z78k5utxYyOOYkyGJQO3MMjOsGr1Z8mu55OQo6tqHWb6PkJBgRIAsf9mU0CAnZTUQHbCR+ihcTXjMXy3uT8RAxlQqOsaHkQWaI8yjI9hZLzH1cogUdQVE0We8j5W1QeroyJ34VclTc5aTvevOZ3ruIDTglkTA3Cx/NxJytCd+x9/ICIjj5/3GLlmfrL/d7yzeRc8iURZv+EmTXVzLPVEBq3wafVYRlK/UkwgDOwsUJngRyu1YlMhLcYES9/bZunwgxAqWN3SPMAQveRuyBkc7TBiHZKrqohgXnmT+wsiQmA3PAyjXYeRnO9/j+Y98vZxkGM9Tbm9J4GHJtH7xpwNpFH2PwAsj8AaFPSEBMiAfo9GUdEQIInQGsyR0Tk9RLAHbJ53kYHLH5qStqosQycTyvdK5ula6cY7mpS9PNWjYHdjrpD1ILNNUiHRrGUKge4kuxSDBPsUIPphNbyFp9Rg6qYSunCEtQ1Cclr+hLawyRmx8DX2nJEiwb+8Sx826QYzYjg1F13XG1HlT7kl7OhcjEFb8VjYqfXCb1L1YwvvSG8YHpWXSmLKxYN7nFONXMM0O2atdvE/GMPQLMmR8epMxlw4I+zCiWLV6OdMTj8Q0oDIG27XEtzW4JazkimfY=
  matrix:
    - HELM_VERSION=2.16.7
    - HELM_VERSION=3.4.1
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - MAIN_TAG="${SUNSTONE_VERSION}-${HELM_VERSION}-${KUBECTL_VERSION}"
  - HELM_VERSION_MAJOR=`echo $HELM_VERSION | cut -d'.' -f1`
  - |
    docker build -f Dockerfile.helm${HELM_VERSION_MAJOR} . \
      -t digillect/sunstone-helm-kubectl:${MAIN_TAG} \
      -t digillect/sunstone-helm-kubectl:helm${HELM_VERSION_MAJOR} \
      --build-arg SUNSTONE_VERSION=${SUNSTONE_VERSION} \
      --build-arg HELM_VERSION=${HELM_VERSION} \
      --build-arg KUBECTL_VERSION=${KUBECTL_VERSION}
  - docker push digillect/sunstone-helm-kubectl:${MAIN_TAG}
  - docker push digillect/sunstone-helm-kubectl:helm${HELM_VERSION_MAJOR}
